"""empty message

Revision ID: 1a44f08ee976
Revises: 99f097824a3a
Create Date: 2020-03-26 00:08:53.054598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a44f08ee976'
down_revision = '99f097824a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('needy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('cnic', sa.Text(), nullable=False),
    sa.Column('need', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic')
    )
    op.drop_table('Needy')
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('pin', sa.String(length=128), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'pin')
    op.drop_column('users', 'name')
    op.create_table('Needy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Needy_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('cnic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('need', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Needy_pkey'),
    sa.UniqueConstraint('cnic', name='Needy_cnic_key')
    )
    op.drop_table('needy')
    # ### end Alembic commands ###
