"""empty message

Revision ID: dbd86ad571d9
Revises: 52e6577a8d1f
Create Date: 2020-03-26 03:36:13.694851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd86ad571d9'
down_revision = '52e6577a8d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('needy', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('needy', 'address')
    # ### end Alembic commands ###
